my_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: accountid
      user: username
      password: password
      role: ACCOUNTADMIN
      database: ecommerceAnalytics
      warehouse: COMPUTE_WH
      schema: RAW
      threads: 1
      client_session_keep_alive: False
